### ISSUE TITLE
Cannot read property 'ignore' of undefined

### ISSUE THREAD

**Issue by IvanNorin** [svoboda-rabstvo/ngx-translate-lint#100]
# Bug report

## Describe the bug

When I am using: npx ngx-translate-lint --zombies 'error'
I am getting error: TypeError: Cannot read property 'ignore' of undefined
 at Cli.runCli (..\node_modules\ngx-translate-lint\dist\src\cli\cli.js:65:66)
    at Function.run (..\node_modules\ngx-translate-lint\dist\src\cli\cli.js:40:13)
    at Object.<anonymous> (..\node_modules\ngx-translate-lint\dist\src\cli\bin.js:6:11)

My current ngx-translate-lint version "1.14.0".

## To Reproduce

1. npx ngx-translate-lint --zombies 'error'

## Expected behavior

All work fine

**Comment by svoboda-rabstvo** [comment]
Hi @IvanNorin, thanks for issue. I will fix it today. 

If you need right now, you can create config file and setup all settings

**Comment by IvanNorin** [comment]
Hi @svoboda-rabstvo, thanks

**Comment by svoboda-rabstvo** [comment]
Hi @IvanNorin again. I fixed it on `1.14.1`
