### ISSUE TITLE
Create new release including regexp in ignoredKeys

### ISSUE THREAD

**Issue by sebd71** [svoboda-rabstvo/ngx-translate-lint#114]
Hi,
I just want to know if it's possible to create a new release including improvements (regexp support in ignoredKeys) ?
I would like to use this really useful feature (#112) but I cannot because it's not part of any release.

Thanks in advance.

**Comment by tgwittman** [comment]
@svoboda-rabstvo, can we please release this feature 🙏

**Comment by julianpoy** [comment]
@julianpoy/ngx-translate-lint has the fix released to `npm`

**Comment by svoboda-rabstvo** [comment]
@tgwittman @julianpoy 

Release created like `1.15.0`. Pls check the solution.
