### ISSUE TITLE
Yarn run error "env: node\r: No such file or directory"

### ISSUE THREAD

**Issue by NolanRoose** [svoboda-rabstvo/ngx-translate-lint#124]
# Bug report

## Describe the bug

Since versions higher than 1.14.1, impossible to launch "ngx-translate-lint" on Unix/Mac OS environment.

## To Reproduce

- Go on Unix/Mac OS system
- Install last version of ngx-translate-lint
- Run it

## Expected behavior

Lint translation file as well

## Screenshots

<img width="680" alt="Capture d’écran 2022-10-17 à 14 04 54" src="https://user-images.githubusercontent.com/14938257/196173324-abd52874-6050-44c8-a563-6f1b083c002d.png">

<img width="143" alt="Capture d’écran 2022-10-17 à 14 05 13" src="https://user-images.githubusercontent.com/14938257/196173374-d851da76-2aab-4f62-9c58-21bb063974b7.png">

**Comment by svoboda-rabstvo** [comment]
Hi @NolanRoose , could you pls share  config for linter ?

**Comment by NolanRoose** [comment]
```
{
  "rules": {
    "views": "error",
    "zombies": "disable",
    "misprint": "error",
    "maxWarning": "0",
    "misprintCoefficient": "0.9",
    "ignoredKeys": [],
    "ignoredMisprintKeys": [],
    "ast": {
      "isNgsTranslateImported": "error"
    }
  },
  "tsconfig": "./src/tsconfig.app.json",
  "project": "./src/app/**/*.{html,ts}",
  "languages": "./src/assets/i18n/*.json"
}
```

**Comment by svoboda-rabstvo** [comment]
Hi @NolanRoose,

Looks very interesting, because I can't reproduce your case. 
I tested on `MacOS` with your version of `Node.js` and `npm`

Are you sure that bag is reproduced with the latest version of `ngx-translate-lint` ? 

Last version is `1.18.1.`

try to install

```
npm install ngx-translate-lint@1.18.1 --global
```
or 
```
npm install ngx-translate-lint@1.18.1 --save-dev
```

**Comment by NolanRoose** [comment]
Hi @svoboda-rabstvo , this is strange because before posting this bug, I tested on the workstation of two of my colleagues, one on ubuntu and one on windows.

On the windows computer no problem, but on the ubuntu computer I have the same problem as on my mac.

I'll test again on my post, and I'll keep you informed.

**Comment by svoboda-rabstvo** [comment]
Hi @NolanRoose, thanks a lot! I will wait.

**Comment by NolanRoose** [comment]
Hi @svoboda-rabstvo , I still have the same problem with the latest version 1.19.0.

**Comment by svoboda-rabstvo** [comment]
Hi @NolanRoose, are you checked `1.19.0` version on `Mac` ? If yes, pls let me know your device. 

But, mb It's problem on `Mac` or `ngx-translate-lint`... It's maybe `yarn` error

**Comment by NolanRoose** [comment]
Hello, yes i check 
<img width="275" alt="Capture d’écran 2022-11-07 à 12 50 56" src="https://user-images.githubusercontent.com/14938257/200303998-a3ff84b6-83b9-4409-b8f9-2f8547d452a0.png">
<img width="1224" alt="Capture d’écran 2022-11-07 à 12 51 39" src="https://user-images.githubusercontent.com/14938257/200304017-df97062a-a0cb-455d-83b7-4ceaf2946d72.png">
<img width="568" alt="Capture d’écran 2022-11-07 à 12 53 02" src="https://user-images.githubusercontent.com/14938257/200304037-56f2f8bb-e78d-4381-bedb-a5a24511c269.png">
<img width="568" alt="Capture d’écran 2022-11-07 à 12 53 12" src="https://user-images.githubusercontent.com/14938257/200304047-3ed4f163-4b14-4db2-97dd-05b7f6df898c.png">
<img width="568" alt="Capture d’écran 2022-11-07 à 12 53 45" src="https://user-images.githubusercontent.com/14938257/200304071-8f40f85e-e012-40d9-b854-998b575f181d.png">

**Comment by NolanRoose** [comment]
Hello @svoboda-rabstvo ! I switched to yarn v2+ and I don't have the problem anymore! Thanks for your time investigating! And keep up the good work! It's very helpful!

**Comment by svoboda-rabstvo** [comment]
Hi @NolanRoose thanks a lot! That nice to hear!
