### ISSUE TITLE
[QUESTION] Failed to read entry point info from invalid 'package.json'

### ISSUE THREAD

**Issue by NolanRoose** [svoboda-rabstvo/ngx-translate-lint#135]
`Warning: Failed to read entry point info from invalid 'package.json' file: /opt/atlassian/pipelines/agent/build/node_modules/ngx-translate-lint/dist/package.json
`

Hello @svoboda-rabstvo , it's me again, I have this warning during a build in AOT production mode, have you ever had this feedback ?

<img width="1170" alt="Capture d’écran 2022-11-08 à 10 55 28" src="https://user-images.githubusercontent.com/14938257/200533496-d20b8c90-6dac-459f-8ce8-61915fe2a557.png">

**Comment by svoboda-rabstvo** [comment]
Hi @NolanRoose, 

This warning only on version `1.20.0` ?

**Comment by NolanRoose** [comment]
Hello @svoboda-rabstvo , yes

**Comment by NolanRoose** [comment]
thanks you

**Comment by svoboda-rabstvo** [comment]
@NolanRoose Hi, I fixed a problem with the version flag, which included parsing `package.json` file. Could you pls check if this case reproduces on the last version of the release (`1.20.2`) ?

**Comment by NolanRoose** [comment]
@svoboda-rabstvo Hello ! Its good ! The warning disappeared on ^1.20.3 ! Thanks you !

**Comment by svoboda-rabstvo** [comment]
@NolanRoose you are welcome, and have a nice day
