### ISSUE TITLE
Incorrect version is always printed incorrectly

### ISSUE THREAD

**Issue by bencekiss** [svoboda-rabstvo/ngx-translate-lint#136]
# Bug report

## Describe the bug

Running `ngx-translate-lint -v` with any accepted flags outputs the version of the containing package.json, not the version of the package itself.

## To Reproduce

- Create new angular project: `ng new test-ngx-translate-lint` (or use an existing one)
- Run `npm install ngx-translate-lint -g`
- Navigate to the project's directory
- Run `ngx-translate-lint -v` and it outputs `Current version: 0.0.0` in the new project
- Update this new project's package.json version to `1.1.1`
- `ngx-translate-lint -v` will output `Current version: 1.1.1`

- Nitpick: this version number [gets logged to the console](https://github.com/svoboda-rabstvo/ngx-translate-lint/blob/develop/src/cli/cli.ts#L124) on every cli run.

## Expected behavior

Regardless of where `ngx-translate-lint -v` is run, it should always output the `ngx-translate-lint` version. If the latest version is installed, currently it should output `Current version: 1.20.0`. It also shouldn't _always_ log the version number to the console.

## Screenshots

![Screen Shot 2022-11-10 at 14 02 35](https://user-images.githubusercontent.com/24904361/201184259-14fc9556-8c33-49c1-afce-4cb06e221f26.png)

**Comment by svoboda-rabstvo** [comment]
Hi @bencekiss thanks a lot for the issue! I will fix it as soon as possible. :)

**Comment by svoboda-rabstvo** [comment]
Hi @bencekiss , pls check. 

Fixed on release `1.20.2.`

**Comment by bencekiss** [comment]
Hey @svoboda-rabstvo thanks for the fix!

**Comment by svoboda-rabstvo** [comment]
@bencekiss you are welcome :)
