### ISSUE TITLE
Error code is returned when number of warnings is equal to `max-warning` value

### ISSUE THREAD

**Issue by zford-reitz** [svoboda-rabstvo/ngx-translate-lint#28]
# Bug report

## Describe the bug

Running ngx-translate-lint always results in an error return code, due to the fact that the check for 'max-warning' checks whether the warning count is greater than **or equal to** 'max-warning'.

## To Reproduce

Run ngx-translate-lint (without setting an explicit value for 'max-warning') on a project that has no errors and no warnings.

## Expected behavior

I would expect the linter to return an "OK" code (0) if no errors and no warnings occur.

## Screenshots

N/A

## Additional context

Current workaround is to configure 'max-warning' with a value of '1', as opposed to using the default value of '0'.

**Comment by svoboda-rabstvo** [comment]
Thanks for the issue. I will check it today or tomorrow and fix it  soon as possible

**Comment by zford-reitz** [comment]
Thanks for the extremely quick response and fix. Looking at the commit, I think it will solve the problem that I was experiencing. But I also want to point out that the code still doesn't quite match the documentation. According to the docs, an error status will be reported if the number of warnings are greater than the defined 'max-warning'. It looks to me like the code is still checking for ">=" when it should just be ">". So if I define 'max-warning' as 2, I would expect an OK result if 2 warnings occur...I wouldn't expect an error result until 3 or more warnings occur.

**Comment by svoboda-rabstvo** [comment]
You are absolutely right. I will improve docs or codeю Thanks a lot for your contribution :)
