### ISSUE TITLE
Incorrect behaviour with --zombies 'error'

### ISSUE THREAD

**Issue by dvabuzyarov** [svoboda-rabstvo/ngx-translate-lint#55]
# Bug report

## Describe the bug
npx ngx-translate-lint --zombies 'error' exits with 0

according to the doc it should exit with 1 when some missed keys are present 
## To Reproduce
npx ngx-translate-lint --zombies 'error'

## Expected behavior
returns 1 when some missed keys are found

**Comment by svoboda-rabstvo** [comment]
Hi @dvabuzyarov , can you please let me know example behavior with config. 

Thanks a lot!

**Comment by svoboda-rabstvo** [comment]
@dvabuzyarov I fixed it. Please check :)
