### ISSUE TITLE
The `translate` directive inside html tags is sometimes not detected by the tool

### ISSUE THREAD

**Issue by cdarras** [svoboda-rabstvo/ngx-translate-lint#86]
# Bug report

## Describe the bug

The `translate` directive inside html tags is not detected by the tool for somewhat complex tags.

## To Reproduce

Create a html file with the following content:

`<mat-label fxLayoutAlign.xs="center center" [value]="test" translate anotherDirective>translation.key</mat-label>`

Launch the linter on the project.

## Expected behavior

The missing translation `translation.key` should be detected.

**Comment by svoboda-rabstvo** [comment]
Hi @cdarras, thanks a lot for your problem. 

I released `1.11.1` version. It must be help you, please check

**Comment by cdarras** [comment]
Hi!
Unfortunately the tool is now also matching false positives, like these ones:

`<div class="error-code">404</div>`
`<mat-icon class="s-16">chevron_right</mat-icon>`

**Comment by cdarras** [comment]
I've had success with this regexp:

`(?<=<[^<]*\\s+translate(\\s+[^>]*)*>\\s*)([a-zA-Z0-9_.]*)(?=\\s*<\\s*\\/.*\\s*>)`

**Comment by svoboda-rabstvo** [comment]
Hi, @cdarras! 

Your are the best %)

your regexp working for all my keys. I pushed changes right now.

**Comment by svoboda-rabstvo** [comment]
@cdarras, Check please. Current version is `1.11.2`

**Comment by cdarras** [comment]
I have launched the linter on my project (~100 html files), but 2 hours later it was still running so I killed it.

**Comment by svoboda-rabstvo** [comment]
@cdarras I know about this problem, you are absolutely right. Please install previous version. I fixed this problem on `1.11.3` soon

**Comment by svoboda-rabstvo** [comment]
@cdarras I publiched `1.11.3` please check

**Comment by cdarras** [comment]
It works fine, thanks :)

**Comment by svoboda-rabstvo** [comment]
@cdarras you are welcome)
