### ISSUE TITLE
Incorrect behaviour with component mat-icon

### ISSUE THREAD

**Issue by IvanNorin** [svoboda-rabstvo/ngx-translate-lint#92]
# Bug report

## Describe the bug

When I am using `<mat-icon>keyboard_arrow_down</mat-icon> ` on the view , I am getting 
 Key: 'keyboard_arrow_down' doesn't exist in 'en.json' in console log

## To Reproduce

1. Use `<mat-icon>keyboard_arrow_down</mat-icon>` on the view
2. npx ngx-translate-lint --zombies 'error'

## Expected behavior

Ignore component mat-icon for translation, because name icon one for all languages.

**Comment by svoboda-rabstvo** [comment]
Hi @IvanNorin, what version of `ngx-translate-lint` do you use?

**Comment by IvanNorin** [comment]
Hi @svoboda-rabstvo, I am using 1.11.5 version of `ngx-translate-lint` .

**Comment by svoboda-rabstvo** [comment]
@IvanNorin, can you please send all component. Because I can't reproduce your issue

**Comment by IvanNorin** [comment]
@svoboda-rabstvo, yes sure. 
This simple component reproduce error - ` Key: 'keyboard_arrow_down' doesn't exist in 'en.json'`
`<div *ngFor="let name of names">
      {{name | translate}}
      <mat-icon matChipRemove>keyboard_arrow_down</mat-icon>
    </div>`

**Comment by svoboda-rabstvo** [comment]
Thanks a lot! I will fix it soon and write you

**Comment by IvanNorin** [comment]
> Thanks a lot! I will fix it soon and write you

@svoboda-rabstvo, Thanks

**Comment by svoboda-rabstvo** [comment]
Hi @IvanNorin , I released `1.12.0` please check

**Comment by IvanNorin** [comment]
Hi @svoboda-rabstvo, thanks! Now it works fine.
